import os

from dotenv import load_dotenv

load_dotenv()

AUDIO_STYLE = os.getenv("AUDIO_STYLE")
AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")
AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
GPT_MODEL_API_VERSION = os.getenv("GPT_MODEL_API_VERSION")
GPT_MODEL_NAME = os.getenv("GPT_MODEL_NAME")

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
OPENAI_ENDPOINT = os.getenv('OPENAI_ENDPOINT')
TTS_API_VERSION = os.getenv("TTS_API_VERSION")
TTS_MODEL_NAME = os.getenv("TTS_MODEL_NAME")
WHISPER_API_VERSION = os.getenv("WHISPER_API_VERSION")
WHISPER_MODEL_NAME = os.getenv("WHISPER_MODEL_NAME")

ELEVEN_LABS_API_KEY = os.getenv("ELEVEN_LABS_API_KEY")
ELEVEN_LABS_MODEL_NAME = os.getenv("ELEVEN_LABS_MODEL_NAME")
ELEVEN_LABS_VOICE_ID = os.getenv("ELEVEN_LABS_VOICE_ID")
ELEVEN_LABS_OUTPUT_FORMAT = os.getenv("ELEVEN_LABS_OUTPUT_FORMAT")

PINECONE_API_KEY = os.getenv("PINECONE_API_KEY")
PINECONE_INDEX_ENDPOINT = os.getenv("PINECONE_INDEX_ENDPOINT")
PINECONE_INDEX_NAME = os.getenv("PINECONE_INDEX_NAME")
PINECONE_EMBEDDING_MODEL_NAME = os.getenv("PINECONE_EMBEDDING_MODEL_NAME")

THRESHOLD = 0.9